### ISSUE TITLE
Data loss due to unclean shutdown

### ISSUE THREAD

**Issue by lx30011** [linuxserver/docker-qbittorrent#196]
A qbittorrent instance saves its state on shutdown (SIGINT, SIGTERM). How long this process takes depends on the number of torrents that are loaded. According to a maintainer on Discord the container is set up in a way to SIGKILL qbittorrent-nox after 5 seconds. Once you reach a certain threshold of loaded torrents qbittorrent-nox will take longer than 5 seconds to save its state. This means it will be killed before it has fully saved its state. This leads to data loss. The threshold isn't easy to determine because it varies depending on hardware and version of qbittorrent/the libraries used. I would say it's anywhere between 500 and 5000 torrents. Those aren't very high numbers making this a significant issue. According to the maintainer the issue lies in the way s6 is set up. I propose removing the timeout entirely.

**Comment by aptalca** [comment]
Assuming you're the same guy from discord, didn't you already increase the timeout to 20+ seconds and it still wasn't shutting down properly?

That s6 timeout was active before this image was updated to s6v3 but it doesn't seem to be active on s6v3 since your container by default takes 11 seconds to shut down. So the only timeout you're hitting is the imposed by docker (which you already changed).

Combined by the fact that no one else ever reported this, I'm gonna venture a guess that there's something funny going on in your setup that prevents qbit from stopping gracefully.

**Comment by lx30011** [comment]
When I increase the docker timeout the containers take their time to shut down. Some of them take over a minute. Yet I find all my torrents gone on next startup. The directories are writable by the docker process and the files get written. I don't know what the issue is but I presume it must be my setup if no one else has ever reported this. The container should be popular enough for that to happen should it be an issue.

Though I want to add that I tried running qbittorrent natively using a static build from the qbittorrent-nox-static repo and several ones I built myself and none of them performed well. All of them were very slow, the qbittorrent-nox-static ones had severe issues like not having the torrents load in the Web UI. It's a nearly stock configuration Debian VM, I don't see any issue. Though again I know people are running qbittorrent successfully else this static repo wouldn't exist.
