### ISSUE TITLE
[BUG] WebUI\AuthSubnetWhitelist stop working

### ISSUE THREAD

**Issue by 362227** [linuxserver/docker-qbittorrent#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WebUI\AuthSubnetWhitelist stop working

### Steps To Reproduce

edit "qBittorrent.conf" 
add "WebUI\AuthSubnetWhitelist=6.187.0.0/24, 27.246.87.236/32, 6.187.4.21/32"
restart docker, work fine
If restart the VPS , qBittorrent.conf no change, but 6.187.0.0/24, 27.246.87.236/32, 6.187.4.21/32 stop working

### Environment

```markdown
- OS:centos7
- How docker service was installed: YUM
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d   --name=qbittorrent   -e PUID=0   -e PGID=0    -e TZ=Asia/Shanghai   -e WEBUI_PORT=8080   -p 8080:8080   -p 6890:6890   -p 6890:6890/udp   -v /:/config   -v  /:/downloads   --restart unless-stopped   lscr.io/linuxserver/qbittorrent:latest
```

### Container logs

```bash
No logs
```

**Comment by hauserkristof** [comment]
+1

**Comment by drizuid** [comment]
OP provided no logs, is using unsupported PUID/PGID combos, has overlapping bind mounts, installed docker from the repo which gives extremely old versions, and is using centos. We test and support debian based distros and docker installed from the official repo only.

I suggest looking into selinux and apparmor since you're on centos, upgrading your docker version by using the official repo, and properly filling out the issue template in the future.
