### ISSUE TITLE
[FEAT] Use multi-stage docker builds to decrease image size

### ISSUE THREAD

**Issue by mathbunnyru** [linuxserver/docker-qbittorrent#219]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

There is a Docker feature called [multi-stage builds](https://docs.docker.com/build/building/multi-stage/).
Currently the image size is ~90MB compressed (for one arch).

I think some things might be left after building `unrar` and they are not needed in the end.
Also, I'm not sure why some things are installed at all (like `python`)
By using multi-stage docker builds we can not worry about cleaning up and have the perfect image in the end without leftovers.

### Reason for change

Save network traffic/space, make the image faster to startup on slow internet connections.
And also, this is a cleaner design.
For example, if we need to build unrar from source and only need binary in the end, we can have a stage, which builds unrar.

**Comment by aptalca** [comment]
Everything is cleaned up in the same layer. No need for multi state.

Unrar is intended for runtime.

**Comment by thespad** [comment]
Python is included because lots of post-processing scripts require it and when we've tried to remove it in the past the number of complaints have been excessive. Beyond that, the image is optimised as much as possible given the packages we have to install.

Anyway, if we moved to a multi-stage build model for unrar it would reduce the uncompressed image size by a whole 5Mb
```
local/qbt                                       multi                       ea89d6628292   7 seconds ago   231MB
lscr.io/linuxserver/qbittorrent                 latest                      e723e10a071e   6 days ago      236MB
```
And actually I can make that saving anyway without a build stage because it's just a case of duplicate packages getting installed by multiple meta-packages.
```
local/qbt                                       buildbase                   6e6165704e29   26 seconds ago   231MB
```
