### ISSUE TITLE
[BUG] <New Install, possible UI Bug as result of default password changes?>

### ISSUE THREAD

**Issue by mousethatischarles** [linuxserver/docker-qbittorrent#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Debianx64-based OS (DietPi x64) on ESXi 7u3 Migrating over to a new server install:

qBittorrent Docker running fine on old install... yes, yes... I changed the default qBittorrent WebUI password!
New docker pull: ghcr.io/linuxserver/qbittorrent:latest resulting in v4.6.3-r0-ls306 - bare install is functional.
Configs folder transferred across from old install and:
1) Unable to log in to WebUI with either old password or adminadmin
2) On reload "Unauthorized"
->Returning to default config results in same issue, usual fix for "Unauthorized" does work but still unable to log in to WebUI
->The usual password fix no longer available as qBtrorrent.inf no longer contains the relevant lines to reset - why? I believe this is a deliberate change and password details are now 'hidden' elsewhere to be loaded on start up.
sigh
-> qBitorrent (seemingly) fully uninstalled and then reinstalled from scratch - I'll now have to manually re-enter all my torrents and settings from scratch rather than transfer them across (bug report #1)
-> But, No. The unrecognised adminadmin password 'feature' remains even with a new and hopefully 'clean' install. My old password also not working. (either with fully new Config folder or my old one) I presume the 'hidden' location is not expunged on an uninstall and so the issue will now forever remain unless I a) know where this (IMO unnecessary and frustrating) change has been hidden or I fully reinstall the OS! (bug report #2)
For now I'll try with an earlier (IMO non-broken) version, take care not to 'upgrade', and see how that goes.

All the best.

### Expected Behavior

see above

### Steps To Reproduce

see aove

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
see above
```

### Container logs

```bash
see aove
```

**Comment by Roxedus** [comment]
https://github.com/linuxserver/docker-qbittorrent#application-setup

**Comment by geebru** [comment]
@Roxedus Replying to that link since I'm having a relevant but slightly different setup issue:

I'm running this image via Container Manager in my Synology DS220+. For about a month, the setup was fine, my login worked and things were great. Starting this weekend, I had an issue where my saved credentials wouldn't work, but neither would the temporary ones from the logs. Yesterday I updated to the latest version of the image in hopes it would fix it but no luck.

If I do a full re-build and reset I can use the logged temp to re-log in, change my account, and use that. But after a period of inactivity, it seems to slide back into invalid credentials. I know nothing truly happens randomly but I'm at a loss to figure out why qB suddenly seems to be losing the credentials information.

_I also see this was marked invalid due to not following the template but wanted to chime in that I've done the setup a few times now per the docs and it still resets or loses my credentials._

**Comment by will-molloy** [comment]
Same here, can't login with the default password given.

**Comment by xilmen** [comment]
Hi, 

Have you tried using another browser or clearing the cache/cookies/session?

![firefox_edN81KftK3](https://github.com/linuxserver/docker-qbittorrent/assets/14809093/50d198ba-1e5a-456f-8f46-bf49f0a11f55)

**Comment by shareit** [comment]
It is reproducing also on my side. I'm not able to login in a browser (also in incognito) with the generated password from the terminal.
Do you know what is the stable version without this issue? I was using in the past qbittorrent (with :latest tag) in docker and it was great.

**Comment by j0nnymoe** [comment]
If we don't get any logs or compose snippets, it's hard for us to look into. The original post was marked invalid because not enough information was provided, if people container just to say same here without providing the missing info, we can't attempt to move this forward.

**Comment by atomass** [comment]
I would like to report the "same" issue: after an upgrade (`docker compose pull`) my old password did not work anymore and I couldn't see any temporary one in the logs.
So, what I did in order to solve the issue was
1. backup the config folder: `mv config config_backup`
2. delete the qbittorrent image: `docker image rm lscr.io/linuxserver/qbittorrent:latest`
3. start the docker `docker compose up -d --remove-orphans`
4. check the logs for the temporary password: `docker compose logs` (it was there this time!)
5. change the password in the WebUI settings
6. stop the container `docker compose down`
7. copy the `WebUI\Password_PBKDF2=....` line from the new `config/qBittorrent/qBittorrent.conf` to the backup one
8. revert backup the backup config
9. profit

While this is an hacky workaround, I think that the update process of this docker has a "bug".

**Comment by yorktownting** [comment]
Same "Unauthorized" when I use a docker-compose to up the container in Windows' docker desktop. I am unable to change the default random password 💔

**Comment by carlos-garcia** [comment]
I am having the same issue and after finding the default password on the logs, all my torrents are gone!.. even worse, if i put a new password on the UI, after restarting the container, the configuration is gone and there a new default password again.

**Comment by tchap2** [comment]
I am reporting identical problem when installed as a Docker in UNRAID OS. Upon fresh install of the app, I opened qBittorent->logs->qbittorrent.log with a text editor. There was NO password.

Why not simply have a password set at: "adminadmin"? Whoever does not change that "temp" password, it's their fault. Why complicate?

Also @j0nnymoe,....there are no logs to provide! The log file is EMPTY! You are asking for something that cannot be provided.

It is obvious that the app defies common sense when using it the first time - it's like we're in a 1990 movie.
