### ISSUE TITLE
Moving files slow

### ISSUE THREAD

**Issue by evlo** [linuxserver/docker-qbittorrent#53]
With docker using native paths, if I move torrent from /mnthdd/shows to /mnt/movies it is instant. When I mapped that paths to /shows and /movies and then move from /shows to /movies it is super slow, like 10 or 20 MBPs.

**Comment by Dulanic** [comment]
So this can be caused by multiple things. 

- By using seperate volumes, many times the mv command thinks its different devices so it does a cp / delete more so than a move. This may be addressed (possibly) by my comment below about mergerfs.

- Docker inherntly has a slow write process that eats up CPU cycles. This is a WIP.

One thing you may try is to use mergerfs to creeate 1 path to mount and have it combine multiple paths... this works pretty well for me.

https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076
