### ISSUE TITLE
New API breaks Sonarr and radarr 

### ISSUE THREAD

**Issue by fumantsu** [linuxserver/docker-qbittorrent#62]
With the new 4.2.0 version a new API has been introduced that many applications has yet adopt so communication between qbittorrent and Sonarr/Radarr doesn't work. 

I think the best is to have a new branch/tag with the previous version (clear tag) for all these that doesn't work to upgrade (my case was accidental upgrade of the container).

**Comment by thelamer** [comment]
The last stable 4.1 tag is `4.1.9.99201911190849-6738-0b055d8ubuntu18.04.1-ls54`

Use this if you don't want 4.2.

The developers have seen fit to mark 4.2 stable , I am confident functionality and workarounds will come in due time. 

Us maintaining a specific short tag pinned to this version would only serve to slow or stop that progress.

**Comment by CHBMB** [comment]
FWIW I agree with @thelamer 

It's the whole point of having a repository of tagged releases, you can pin your version and upgrade to `latest` when it's stable for you.

**Comment by fumantsu** [comment]
Yes, I found it as well (after some small effort to pick up) the previous stable tag. It is just bit confusing how are the tags in docker hub (log names etc). That's why I suggested something more smaller and easier.
@CHBMB Thanks a lot for the typo... brakes :D

**Comment by aptalca** [comment]
@fumantsu the tag consists of the app version tag we retrieve from upstream `4.1.9.99201911190849-6738-0b055d8ubuntu18.04.1` in this case and a build version `ls54`. So when there is an OS package update and therefore a new build, the app version will remain the same, but the build version will increment to `ls55`. But due to multi-arch, there will be multiple images for each release.

Github releases can be a little easier to navigate each release: https://github.com/linuxserver/docker-qbittorrent/releases
There, you'll have to pay attention to `stable` versus `pre-release` tags
