### ISSUE TITLE
How to interpret the qBittorrent and libtorrent version from your docker tags?

### ISSUE THREAD

**Issue by skygunner** [linuxserver/docker-qbittorrent#92]
Is the 14.3.2 means 4.3.2?
How about libtorrent version and OS version?

Just need to test for several bugs for development/testing purpose. But the tags is a bit confusing.

**Comment by Roxedus** [comment]
Yes. The version is extracted from qbittorrents apt package, that's where the weird number comes from.

You can find the current version of libtorrent in the https://github.com/linuxserver/docker-qbittorrent/blob/master/package_versions.txt file. And the OS is currently Ubuntu Bionic (https://github.com/linuxserver/docker-qbittorrent/blob/master/Dockerfile#L1).

**Comment by skygunner** [comment]
Thanks for quick explanation. 
For example a tag reads version-14.3.0.99202011251333-7141-587688634ubuntu18.04.1
end libtorrent package version libtorrent-rasterbar101.2.12+git20210104.bfafd20428-1ppa1~18.04
They doesn't play well. If there's any way could make the libtorrent package version more obvious readable before pulling it down, it will be nice. Cheers,

**Comment by Roxedus** [comment]
I don't see that happening. We want the package list to be 100% traceable back to which apt package was used, this is the only way to ensure that.

**Comment by aptalca** [comment]
We are not at all concerned with readability. These versions are coming straight from their ppa. If you have an issue with them, you can report it upstream

**Comment by rocketeerbkw** [comment]
I was also confused by the the release numbering in the tags, so here's the process as of now for anyone playing along at home.

> These versions are coming straight from their ppa.

That's true, but I would argue technically incorrect and also not that helpful. The versions go through a [sanitizer](https://github.com/linuxserver/docker-qbittorrent/blob/19e9414071f471a91e16839a87adea173e38eb2c/Jenkinsfile#L112-L121) first, so there isn't a direct match back to the ppa version.

For example, look at the latest release on [launchpad](https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable?field.series_filter=focal) which is `1:4.3.3.99~202101191832-7248-da0b276d5~ubuntu20.04.1` but after processing it ends up as a tag of `version-14.3.3.99202101191832-7248-da0b276d5ubuntu20.04.1`

The major version looks like `14` instead of `4` and the build number (?) looks like `99202101191832` instead of `99` and a date.

Perhaps the sanitizer could use `_` instead of ``? The only reason I came across this is because upgrading to the `latest` broke my qbittorrent and I wanted to do smaller updates to each release to figure out where it first broke.

**Comment by aptalca** [comment]
Right, the sanitizer is just stripping characters that are not accepted by GitHub in tags, release names, etc.
